# Generated by Django 4.2 on 2026-05-04 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prontuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_integridade', models.CharField(blank=True, editable=False, max_length=64, null=True)),
                ('conteudo', models.TextField()),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('FECHADO', 'Fechado')], default='RASCUNHO', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('atendimento', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='prontuario', to='appointments.atendimento')),
                ('finalizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prontuarios_finalizados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdendoProntuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('prontuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adendos', to='medical_records.prontuario')),
            ],
        ),
    ]
