# Generated by Django 4.2 on 2026-04-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prontuario',
            name='hash_integridade',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True),
        ),
    ]
