# Generated by Django 4.2 on 2026-05-07 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('data_hora', models.DateTimeField()),
                ('status', models.CharField(choices=[('AGENDADO', 'Agendado'), ('EM_ATENDIMENTO', 'Em Atendimento'), ('REALIZADO', 'Realizado'), ('CANCELADO', 'Cancelado')], default='AGENDADO', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atendimentos', to='clinics.clinic')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atendimentos', to='patients.patient')),
            ],
        ),
    ]
