# Generated by Django 4.2 on 2026-05-07 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professionals', '0001_initial'),
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='profissional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='atendimentos', to='professionals.professional'),
        ),
        migrations.AddConstraint(
            model_name='atendimento',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'CANCELADO'), _negated=True), fields=('clinic', 'profissional', 'data_hora'), name='unique_active_appointment_per_slot'),
        ),
    ]
