# Generated by Django 4.2 on 2026-04-22 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_atendimento_clinic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atendimento',
            old_name='criado_em',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='atendimento',
            name='dentista',
        ),
        migrations.AddField(
            model_name='atendimento',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
