# Generated by Django 4.2 on 2026-04-22 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0001_initial'),
        ('appointments', '0003_rename_criado_em_atendimento_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='profissional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='atendimentos', to='professionals.professional'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
