# Generated by Django 4.2 on 2026-04-30 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
        ('appointments', '0004_atendimento_profissional_atendimento_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atendimentos', to='clinics.clinic'),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='status',
            field=models.CharField(choices=[('AGENDADO', 'Agendado'), ('EM_ATENDIMENTO', 'Em Atendimento'), ('REALIZADO', 'Realizado'), ('CANCELADO', 'Cancelado')], default='AGENDADO', max_length=20),
        ),
    ]
