# Generated by Django 4.2 on 2026-05-04 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_alter_atendimento_clinic_alter_atendimento_status'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='atendimento',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'CANCELADO'), _negated=True), fields=('clinic', 'profissional', 'data_hora'), name='unique_active_appointment_per_slot'),
        ),
    ]
