# Generated by Django 4.2 on 2026-05-04 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
