# Generated by Django 4.2 on 2026-07-03 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0002_add_clinic_customization'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
