# Generated by Django 4.2 on 2026-04-17 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
        ('audit', '0002_auditlog_severity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinics.clinic'),
        ),
    ]
