# Generated by Django 4.2 on 2026-04-16 12:40

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='cpf',
            field=apps.core.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='document',
            field=apps.core.fields.EncryptedTextField(blank=True, null=True),
        ),
    ]
