# Generated by Django 4.2 on 2026-04-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_cpf_patient_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='cpf_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(fields=('clinic', 'cpf_hash'), name='unique_cpf_per_clinic'),
        ),
    ]
