# Generated by Django 4.2 on 2026-05-04 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('professional', 'Professional'), ('staff', 'Staff')], default='staff', max_length=20),
        ),
    ]
