# Generated by Django 4.2 on 2026-07-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_force_password_change_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='extra_preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='font_size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='primary_color',
            field=models.CharField(blank=True, default='#0651ED', max_length=20, null=True),
        ),
    ]
