# Generated by Django 4.2 on 2026-05-04 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('registration_type', models.CharField(max_length=50)),
                ('registration_number', models.CharField(max_length=50)),
                ('specialty', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professionals', to='clinics.clinic')),
            ],
        ),
        migrations.AddConstraint(
            model_name='professional',
            constraint=models.UniqueConstraint(fields=('clinic', 'registration_type', 'registration_number'), name='unique_registration_per_clinic'),
        ),
    ]
